# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18N3vFAcrIe0L210QgtoK4HBCWqiqfVbX
"""

import socket
import struct

# Create a raw socket to listen to all IP packets
s = socket.socket(socket.AF_INET, socket.SOCK_RAW, socket.IPPROTO_TCP)

while True:
    # Receive packets
    packet, addr = s.recvfrom(65565)

    # Unpack the IP packet
    ip_header = packet[:20]
    iph = struct.unpack('!BBHHHBBH4s4s', ip_header)

    # Extract source and destination IP addresses
    src_ip = socket.inet_ntoa(iph[8])
    dest_ip = socket.inet_ntoa(iph[9])

    print(f'Source IP: {src_ip} Destination IP: {dest_ip}')